nameOverride: ""
fullnameOverride: ""

replicaCount: 1
containerPort: 80

image:
  repository: docker.dev.hybrit.io/hybrit-demo-saleor-storefront
  pullPolicy: Always

imagePullSecrets:
  - name: docker-cfg

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

probes:
  enabled: true
  probePath: /dashboard/
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

env:
  - name: API_URI
    value: "https://demo.core.ecommerce-portal.hybrit.io/graphql/"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50mb
    nginx.ingress.kubernetes.io/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: demo.ecommerce-portal.hybrit.io
      path: /
  tls:
    - hosts:
        - "demo.ecommerce-portal.hybrit.io"
      secretName: "ecommerce-portal-ingress-cert"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80