apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrit-demo-saleor-storefront.fullname" . }}
  labels:
    {{- include "hybrit-demo-saleor-storefront.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{.Values.service.nodePort}}
      targetPort: {{.Values.containerPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "hybrit-demo-saleor-storefront.selectorLabels" . | nindent 4 }}
